In [1]:
from sklearn import preprocessing
import numpy as np
data = np.array([[2.2,5.9,-1.8],[5.4,-3.2,-5.1],[-1.9,4.2,3.2]])

In [2]:
data

array([[ 2.2,  5.9, -1.8],
       [ 5.4, -3.2, -5.1],
       [-1.9,  4.2,  3.2]])

In [11]:
data_l1 = preprocessing.normalize(data,norm='l1')
data_l2 = preprocessing.normalize(data,norm='l2')
print('L1-normalized data:\n',data_l1)
print('L2-normalized data:\n',data_l2)

L1-normalized data:
 [[ 0.22222222  0.5959596  -0.18181818]
 [ 0.39416058 -0.23357664 -0.37226277]
 [-0.20430108  0.4516129   0.34408602]]
L2-normalized data:
 [[ 0.3359268   0.90089461 -0.2748492 ]
 [ 0.6676851  -0.39566524 -0.63059148]
 [-0.33858465  0.74845029  0.57024784]]
